"""add phone number

Revision ID: 2e97d928b77a
Revises: e5a6d575a580
Create Date: 2022-04-11 18:46:22.722343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e97d928b77a'
down_revision = 'e5a6d575a580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
